services:
  db:
    image: mysql:latest
    container_name: db
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: citypoi
      MYSQL_USER: citypoiuser
      MYSQL_PASSWORD: citypoipassword

  backend:
    build: .
    container_name: backend
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn citypoi.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - ./citypoi/:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - nginx
    restart: always
    environment:
      - DEBUG=1
      - DB_NAME=citypoi
      - DB_USER=citypoiuser
      - DB_PASSWORD=citypoipassword
      - DB_HOST=db
      - DB_PORT=3306

  nginx:
    image: nginx:latest
    container_name: webserver
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
      - ./media:/app/media


volumes:
  mysql_data: