# Generated by Django 5.1.1 on 2024-09-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='poi_type',
            field=models.CharField(choices=[('landmark', 'Landmark'), ('park', 'Park'), ('tourist_spot', 'Tourist Spot'), ('attraction', 'Attraction'), ('historic_site', 'Historic Site'), ('cultural_site', 'Cultural Site'), ('shopping', 'Shopping'), ('cultural_village', 'Cultural Village'), ('historic_city', 'Historic City'), ('recreation', 'Recreation')], max_length=50),
        ),
    ]
